import CPUBaselines
import Foundation
import Testing
@testable import GPUQuicksort

@Suite("Oracles") struct OracleTests {

    // MARK: C-04 key codec (CPU half of T-05)

    /// T-05 (CPU half; the GPU round trip is in CorrectnessTests): C-04 encode/decode are exact
    /// inverses on 2^24 sampled patterns including every special class, and encode is monotone
    /// with IEEE 754 totalOrder (checked against Swift's `isTotallyOrdered`) and with Int32 order.
    /// Proves C-04, R-17, E-14.
    @Test func keyCodecRoundTripAndOrder() {
        let specials: [UInt32] = [0, 1, 0x7F7F_FFFF, 0x7F80_0000, 0x7F80_0001, 0x7FC0_0000, 0x7FFF_FFFF,
                                  0x8000_0000, 0x8000_0001, 0xFF7F_FFFF, 0xFF80_0000, 0xFF80_0001,
                                  0xFFC0_0000, 0xFFFF_FFFF, 0x0080_0000, 0x807F_FFFF]
        var patterns = specials
        var x: UInt32 = 0x9E37_79B9
        for i in 0..<(1 << 24) { patterns.append(UInt32(truncatingIfNeeded: i &* 256) ^ (x & 0xFF)); x = x &* 1_664_525 &+ 1_013_904_223 }
        for t in KeyType.allCases {
            for b in patterns { #expect(KeyCodec.decode(KeyCodec.encode(b, t), t) == b) }
        }
        // 64 hand-picked floats, totalOrder checked two ways.
        let floats: [Float] = [
            -.nan, -.signalingNaN, -.infinity, -.greatestFiniteMagnitude, -1e30, -65504, -3.5, -1, -0.5,
            -.leastNormalMagnitude, -.leastNonzeroMagnitude, -0.0, 0.0, .leastNonzeroMagnitude,
            .leastNormalMagnitude, 1e-20, 0.1, 0.5, 1, 2, 3.5, 1000, 65504, 1e30, .greatestFiniteMagnitude,
            .infinity, .nan, .signalingNaN,
            Float(bitPattern: 0x7FFF_FFFF), Float(bitPattern: 0xFFFF_FFFF), Float(bitPattern: 0x7F80_0001),
            Float(bitPattern: 0xFF80_0001),
        ] + (0..<32).map { Float(bitPattern: UInt32($0) &* 0x0813_1001) }
        #expect(floats.count == 64)
        for a in floats {
            for b in floats {
                let ea = KeyCodec.encode(a.bitPattern, .float32), eb = KeyCodec.encode(b.bitPattern, .float32)
                #expect(a.isTotallyOrdered(belowOrEqualTo: b) == (ea <= eb))
            }
        }
        #expect(KeyCodec.encode((-0.0 as Float).bitPattern, .float32) < KeyCodec.encode((0.0 as Float).bitPattern, .float32))
        let ints: [Int32] = [.min, -2, -1, 0, 1, 2, .max]
        let codes = ints.map { KeyCodec.encode(UInt32(bitPattern: $0), .int32) }
        #expect(codes == codes.sorted() && Set(codes).count == codes.count)
    }

    // MARK: C-08 generators (T-25, T-26)

    struct Golden: Decodable { var n: Int; var seed: UInt32; var mt19937_seed5489_first: UInt32; var sha256: [String: String] }

    /// T-25: for each C-08 distribution (n = 1024, seed 42) the SHA-256 of the generated bytes
    /// equals the value computed by the independent Python reference (Fixtures/gen_reference.py),
    /// for uint32 and float32 keys; MT19937 seeded with 5489 yields 3499211612 first.
    /// Proves R-20, C-08.
    @Test func goldenHashes() throws {
        let url = try #require(Bundle.module.url(forResource: "golden", withExtension: "json", subdirectory: "Fixtures"))
        let g = try JSONDecoder().decode(Golden.self, from: Data(contentsOf: url))
        var mt = MT19937(seed: 5489)
        #expect(mt.next() == 3_499_211_612)
        #expect(g.mt19937_seed5489_first == 3_499_211_612)
        for key in [KeyType.uint32, .float32] {
            for d in Distribution.allCases {
                let bits = Distribution.generate(d, n: g.n, seed: g.seed, key: key)
                let data = bits.withUnsafeBufferPointer { Data(buffer: $0) }
                #expect(TS.sha256Hex(data) == g.sha256["\(key.rawValue)/\(d.rawValue)"], "\(key)/\(d)")
            }
        }
    }

    /// T-26: distribution properties for n = 2^20 — all values < 2^31, `sorted` non-decreasing,
    /// `zero` constant, `bucket` section S in [S·w, (S+1)·w), `staggered` block i in the D-07
    /// range, `gaussian` mean within 1% of 2^30. Proves C-08, D-07.
    @Test func distributionProperties() {
        let n = 1 << 20, p = 128, w: UInt64 = 1 << 24
        for d in Distribution.allCases where d != .fullrange {
            let v = Distribution.generate(d, n: n, seed: 42, key: .uint32)
            #expect(v.count == n)
            #expect(v.allSatisfy { $0 < (1 << 31) }, "\(d)")
            switch d {
            case .sorted: #expect(zip(v, v.dropFirst()).allSatisfy { $0 <= $1 })
            case .zero: #expect(Set(v).count == 1)
            case .bucket:
                for k in stride(from: 0, to: n, by: 997) {
                    let s = UInt64(k) * UInt64(p * p) / UInt64(n) % UInt64(p)
                    #expect(UInt64(v[k]) >= s * w && UInt64(v[k]) < (s + 1) * w)
                }
            case .staggered:
                for k in stride(from: 0, to: n, by: 997) {
                    let i = UInt64(k) * UInt64(p) / UInt64(n)
                    let lo = i < UInt64(p / 2) ? (2 * i + 1) * w : (2 * i - UInt64(p)) * w
                    #expect(UInt64(v[k]) >= lo && UInt64(v[k]) < lo + w)
                }
            case .gaussian:
                let mean = v.reduce(0.0) { $0 + Double($1) } / Double(n)
                #expect(abs(mean - Double(1 << 30)) / Double(1 << 30) < 0.01)
            default: break
            }
        }
    }

    // MARK: K-04 / K-05 parameters (T-20, pure half)

    static let limits = DeviceLimits(name: "test", maxThreadsPerThreadgroup: 1024, threadExecutionWidth: 32,
                                     maxThreadgroupMemoryLength: 32768, maxBufferLength: 1 << 34,
                                     maxKeys: Int(Int32.max))

    /// T-20 (pure half; the `resolvedParameters` API half is in APITests): with the paper's
    /// 8800GTX constants, `optp` defaults are (64, 512, 256) for n = 2^20 and (256, 1024, 1024)
    /// for n = 2^24, and the K-04 clamps apply in order T, maxseq, minseq for n = 0 and n = maxKeys.
    /// Proves K-05, K-04, R-16.
    @Test func optpDefaultsAndClamps() throws {
        let c = TunedConstants.paper8800GTX
        func r(_ n: Int) throws -> (Int, Int, Int) {
            let p = try ParameterResolver.resolve(n: n, parameters: .automatic, tuning: c, limits: Self.limits)
            return (p.threadsPerThreadgroup, p.maxSequences, p.minSequenceLength)
        }
        #expect(try r(1 << 20) == (64, 512, 256))
        #expect(try r(1 << 24) == (256, 1024, 1024))
        #expect(try r(0) == (64, 512, 256))
        #expect(try r(Int(Int32.max)) == (1024, 65536, 4096))   // T clamped to 1024; minseq to the K-03 bound
        #expect(ParameterResolver.optp(s: 0, k: 0, m: 1) == 1)
        #expect(ParameterResolver.optp(s: 1000, k: 0.001, m: 7) == 8)   // log2(8) + 0.5 → 3
    }

    // MARK: C-10 tuned-parameter table (T-37, table half)

    static func table(_ json: String) -> Data { Data(json.utf8) }
    static let entry = #"{"fitted":"2026-01-01","gpuqsortVersion":"x","sizes":[1],"threads":{"k":0,"m":64},"maxseq":{"k":0,"m":512},"minseq":{"k":0,"m":256}}"#

    /// T-37 (table half; the `init` half is in APITests): the bundled table validates; tables
    /// without `apple-default`, with k < 0 or m < 1, with a `sameAs` chain, or malformed JSON are
    /// rejected with `tunedParametersInvalid`; an unknown device resolves to `apple-default`'s
    /// target with `exactMatch == false`; the OLS fit gives (2, 1) for (1,3),(2,5),(3,7), k = 0 and
    /// m = mean for decreasing data, and (0, x1) for one point. Proves C-10, E-20, E-21.
    @Test func tunedTable() throws {
        let bundled = try #require(ShaderLibrary.resourceURL("TunedParameters", "json"))
        let t = try TunedTable.decode(Data(contentsOf: bundled))
        let resolved = t.lookup(deviceName: "No Such GPU")
        #expect(resolved.exactMatch == false)
        #expect(resolved.entry == t.defaultTarget)

        let bad = [
            #"{"schema":1,"entries":{"a":\#(Self.entry)}}"#,                                          // no apple-default
            #"{"schema":1,"entries":{"a":\#(Self.entry.replacingOccurrences(of: #""k":0,"m":64"#, with: #""k":-1,"m":64"#)),"apple-default":{"sameAs":"a"}}}"#,
            #"{"schema":1,"entries":{"a":\#(Self.entry.replacingOccurrences(of: #""m":64"#, with: #""m":0.5"#)),"apple-default":{"sameAs":"a"}}}"#,
            #"{"schema":1,"entries":{"a":\#(Self.entry),"b":{"sameAs":"a"},"apple-default":{"sameAs":"b"}}}"#, // chain
            #"{"schema":2,"entries":{"a":\#(Self.entry),"apple-default":{"sameAs":"a"}}}"#,
            #"{"schema":1,"entries":"#,                                                                // malformed
        ]
        for j in bad {
            #expect(throws: GPUQuicksortError.self) { _ = try TunedTable.decode(Self.table(j)) }
        }
        let good = try TunedTable.decode(Self.table(#"{"schema":1,"entries":{"Dev X":\#(Self.entry),"apple-default":{"sameAs":"Dev X"}}}"#))
        let exact = good.lookup(deviceName: "Dev X")
        #expect(exact.exactMatch && exact.entry == "Dev X" && exact.threads.m == 64)
        #expect(good.lookup(deviceName: "Other").exactMatch == false)

        // Round trip through upsert + encode keeps validity.
        let up = good.upserting(name: "Dev Y", entry: good.entries["Dev X"]!.lineEntry!, asDefault: true)
        let again = try TunedTable.decode(up.encoded())
        #expect(again.defaultTarget == "Dev Y")

        let f1 = TunedTable.fitLine(sizes: [1, 2, 3], values: [3, 5, 7])
        #expect(abs(f1.k - 2) < 1e-12 && abs(f1.m - 1) < 1e-12)
        let f2 = TunedTable.fitLine(sizes: [1, 2, 3], values: [9, 6, 3])
        #expect(f2.k == 0 && abs(f2.m - 6) < 1e-12)
        let f3 = TunedTable.fitLine(sizes: [5], values: [128])
        #expect(f3.k == 0 && f3.m == 128)
        #expect(TunedTable.fitLine(sizes: [1, 2], values: [0.1, 0.2]).m >= 1)
    }

    // MARK: C-11 CPU baselines (T-39, baseline half)

    /// T-39 (baseline half; the `bench` debug guard is in CLITests): `cpub_qsort_u32`,
    /// `cpub_stdsort_u32` and `cpu-swift` produce output identical to CPUReference for every C-08
    /// distribution and key type at n ∈ {0, 1, 2, 1000, 10^6}. Proves R-26, C-11.
    @Test func cpuBaselinesMatchReference() {
        for d in Distribution.allCases {
            for key in KeyType.allCases {
                for n in [0, 1, 2, 1000, 1_000_000] {
                    let input = Distribution.generate(d, n: n, seed: 7, key: key)
                    let ref = CPUReference.sortedReference(input, key)
                    for algo in CPUBaseline.allCases {
                        #expect(CPUBaseline.run(algo, input, key) == ref, "\(algo) \(d) \(key) \(n)")
                    }
                }
            }
        }
    }
}
